### ISSUE TITLE
Análisis de Aplicación de WebAR 

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-remi-team-1#1]
[Reporte 1 Aplicación Web AR.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-remi-team-1/files/10768606/Reporte.1.Aplicacion.Web.AR.pdf)

**Comment by ArturoAngonJose** [comment]
calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
